name: "Python (pipenv) Example"
description: "An example pipeline for testing a Python project using pipenv"
emoji: ":python:"
steps:
  - command: "buildkite-agent pipeline upload"
    label: ":pipeline:"
